# .coderabbit.yaml
language: "ja-JP"

reviews:
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
  profile: "assertive"
  high_level_summary: true

chat:
  auto_reply: true

